apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-platform-operator-manager-role
rules:
  - apiGroups:
      - platform.example.com
    resources:
      - applicationenvironments
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - platform.example.com
    resources:
      - applicationenvironments/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - platform.example.com
    resources:
      - applicationenvironments/finalizers
    verbs:
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
