//go:build !ignore_autogenerated

package v1alpha1

import (
	autoscalingv2 "k8s.io/api/autoscaling/v2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *ApplicationEnvironment) DeepCopyInto(out *ApplicationEnvironment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ApplicationEnvironment) DeepCopy() *ApplicationEnvironment {
	if in == nil {
		return nil
	}
	out := new(ApplicationEnvironment)
	in.DeepCopyInto(out)
	return out
}

func (in *ApplicationEnvironment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ApplicationEnvironmentAutoscalingSpec) DeepCopyInto(out *ApplicationEnvironmentAutoscalingSpec) {
	*out = *in
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.TargetCPUUtilizationPercentage != nil {
		in, out := &in.TargetCPUUtilizationPercentage, &out.TargetCPUUtilizationPercentage
		*out = new(int32)
		**out = **in
	}
	if in.Behavior != nil {
		in, out := &in.Behavior, &out.Behavior
		*out = new(autoscalingv2.HorizontalPodAutoscalerBehavior)
		(*in).DeepCopyInto(*out)
	}
}

func (in *ApplicationEnvironmentAutoscalingSpec) DeepCopy() *ApplicationEnvironmentAutoscalingSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationEnvironmentAutoscalingSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ApplicationEnvironmentImageSpec) DeepCopyInto(out *ApplicationEnvironmentImageSpec) {
	*out = *in
}

func (in *ApplicationEnvironmentImageSpec) DeepCopy() *ApplicationEnvironmentImageSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationEnvironmentImageSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ApplicationEnvironmentList) DeepCopyInto(out *ApplicationEnvironmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ApplicationEnvironment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ApplicationEnvironmentList) DeepCopy() *ApplicationEnvironmentList {
	if in == nil {
		return nil
	}
	out := new(ApplicationEnvironmentList)
	in.DeepCopyInto(out)
	return out
}

func (in *ApplicationEnvironmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ApplicationEnvironmentServiceSpec) DeepCopyInto(out *ApplicationEnvironmentServiceSpec) {
	*out = *in
}

func (in *ApplicationEnvironmentServiceSpec) DeepCopy() *ApplicationEnvironmentServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationEnvironmentServiceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ApplicationEnvironmentSpec) DeepCopyInto(out *ApplicationEnvironmentSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	out.Image = in.Image
	out.Service = in.Service
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(ApplicationEnvironmentAutoscalingSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

func (in *ApplicationEnvironmentSpec) DeepCopy() *ApplicationEnvironmentSpec {
	if in == nil {
		return nil
	}
	out := new(ApplicationEnvironmentSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ApplicationEnvironmentStatus) DeepCopyInto(out *ApplicationEnvironmentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconciledTime != nil {
		in, out := &in.LastReconciledTime, &out.LastReconciledTime
		*out = (*in).DeepCopy()
	}
}

func (in *ApplicationEnvironmentStatus) DeepCopy() *ApplicationEnvironmentStatus {
	if in == nil {
		return nil
	}
	out := new(ApplicationEnvironmentStatus)
	in.DeepCopyInto(out)
	return out
}
