apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default/namespace.yaml
  - crd/bases/platform.example.com_applicationenvironments.yaml
  - rbac/service_account.yaml
  - rbac/role.yaml
  - rbac/role_binding.yaml
  - manager/deployment.yaml
  - manager/service.yaml
  - manager/poddisruptionbudget.yaml
  - manager/networkpolicy.yaml
